name: RPG Encode

on:
  push:
    branches: [main]
    paths-ignore:
      - .rpg/graph.json
      - .rpg/embeddings.jsonl

permissions:
  contents: write
  pull-requests: write

jobs:
  encode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install RPG
        run: bun install -g @pleaseai/rpg

      - name: Encode or evolve RPG
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
        run: |
          # Choose embedding model: Voyage API if key available, local nano otherwise
          if [ -n "$VOYAGE_API_KEY" ]; then
            EMBED_MODEL="voyage-ai/voyage-4"
          else
            EMBED_MODEL="transformers/voyageai/voyage-4-nano"
          fi
          EMBED_FLAG="--embed --embed-model $EMBED_MODEL"

          if [ ! -f ".rpg/graph.json" ]; then
            echo "No existing graph — running full encode"
            mkdir -p .rpg
            rpg encode . -o .rpg/graph.json --stamp $EMBED_FLAG
          else
            LAST_COMMIT=$(rpg last-commit .rpg/graph.json 2>/dev/null || echo "")
            if [ -z "$LAST_COMMIT" ]; then
              echo "No commit stamp — running full encode"
              rpg encode . -o .rpg/graph.json --stamp $EMBED_FLAG
            else
              echo "Evolving from $LAST_COMMIT..HEAD"
              rpg evolve --rpg .rpg/graph.json -c "$LAST_COMMIT..HEAD" --stamp || {
                echo "Evolve failed, falling back to full encode"
                rpg encode . -o .rpg/graph.json --stamp $EMBED_FLAG
              }
              # Re-generate embeddings after evolve
              rpg embed --rpg .rpg/graph.json --model $EMBED_MODEL --stamp || true
            fi
          fi

      - name: Create PR with updated graph
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(rpg): update graph"
          title: "chore(rpg): update graph"
          body: "Auto-generated by RPG Encode workflow."
          branch: chore/rpg-update-graph
          add-paths: |
            .rpg/graph.json
            .rpg/embeddings.jsonl
